#!/bin/bash

device=$(tr -d '\0' < /sys/firmware/devicetree/base/model)
case "$device" in
	"Google Minnie") flav=minnie;;
	"Google Kevin") flav=kevin;;
	"Google Bob") flav=todo;;
	*) exit 0;;
esac

[ "$flav" = "todo" ] && exit 0
[ "$flav" = "kevin" ] && exit 0 # need to check /dev/input/by-path

exec /opt/bin/daemon_$flav
