#!/bin/sh
# when tablet mode
if [ "$1" = "T" ]; then
	#swaymsg 'bar 0 font monospace 20'
	#swaymsg input "1267:102:Elan_Touchpad" events disabled
	#swaymsg input "0:0:cros_ec" events disabled
	echo TABLET
fi

# when laptop mode
if [ "$1" = "LP" ]; then
	#swaymsg 'bar 0 font monospace 10'
	#swaymsg input "1267:102:Elan_Touchpad" events enabled
	#swaymsg input "0:0:cros_ec" events enabled
	echo LAPTOP
fi
