#!/bin/sh

if [ "$1" = "R" ]; then
	swaymsg output eDP-1 transform 270
fi

if [ "$1" = "L" ]; then
	swaymsg output eDP-1 transform 90
fi

if [ "$1" = "N" ]; then
	swaymsg output eDP-1 transform 0
fi

if [ "$1" = "T" ]; then
	swaymsg 'bar 0 font monospace 20'
	swaymsg input "1267:102:Elan_Touchpad" events disabled
	swaymsg input "0:0:cros_ec" events disabled
fi

if [ "$1" = "LP" ]; then
	swaymsg 'bar 0 font monospace 10'
	swaymsg input "1267:102:Elan_Touchpad" events enabled
	swaymsg input "0:0:cros_ec" events enabled
fi
